### ISSUE TITLE
[QUESTION]want steps to convert proto to pydantic format in README

### ISSUE THREAD

**Issue by xuxiaoxia96** [anthonycorletti/pydanticprotobuf#3]
### Question
want steps to convert proto to pydantic format in README

confused how to use the Python lib

**Comment by anthonycorletti** [comment]
hey @xuxiaoxia96 ! thanks for your question. I just updated the readme. your q helped me find a pretty big bug. let me know if you're able to use this now. thanks!

**Comment by xuxiaoxia96** [comment]
thanks a lot! you've coded a very awesome python lib！I'll try tomorrow! thanks for your reply!
