### ISSUE TITLE
[QUESTION] some confuse about pydanticprotobuf

### ISSUE THREAD

**Issue by xuxiaoxia96** [anthonycorletti/pydanticprotobuf#4]
hi，I'm Chinese so my English maybe poor~
thanks for your open sourced lib "pydanticprotobuf", it helps me a lot.
but I have some confuse about the lib's usage.

In my opinion, the lib can convert proto to python metadata format。
such as, I provide a proto file
![image](https://user-images.githubusercontent.com/53639856/207297545-91a488f9-d950-4d32-9d2a-33931a3c7ede.png)

use the lib, I can automaticly convert it to python file, with proto3 description.
![image](https://user-images.githubusercontent.com/53639856/207297566-c7cb372e-3d9b-45d7-acd8-2242b3e8538f.png)

but in the example, it probably means, I should declare PersonBase class manually, and the lib can be just used to check the proto type?
![image](https://user-images.githubusercontent.com/53639856/207297580-c4a7610c-754d-457e-9b01-4d3660bcb441.png)

if it can automaticly convert it to python file, I sincerely want your help to teach me the steps ~ thx(*^▽^*)

**Comment by anthonycorletti** [comment]
hey! no worries. you're correct, you would have to write the BaseModel yourself.

to automatically convert this proto file

```proto
// person.proto
syntax = "proto3";
package main;
message Person {
    string name = 1;
    int32 age = 2;
}
```

into this python file

```python
# person.py
class PersonBase(BaseModel):
    name: str 
    age: int 
```

would take more time and energy than I'm able spend on this right now. sorry I couldn't be of more help!

if you'd like to try making this yourself, pull requests are very welcome!
